version: '3.8'

services:
 jenkins:
   image: jenkins/jenkins:lts
   ports:
   - 80:8080
   container_name: jenkins
   volumes:
     - jenkins-data:/var/jenkins_home
   networks:
     - jenkins

volumes:
  jenkins-data:

networks:
  jenkins:
    driver: bridge
